matrix:
  include:
    - language: java
      before_script:
        - cd java
      script:
        - mvn package
      after_success:
        - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    - justin.yan.public@gmail.com